blank_issues_enabled: false
contact_links:
  - name: Please use Discussions to ask questions
    url: https://github.com/zeux/meshoptimizer/discussions/new
    about: Please use Discussions to ask questions
