name: auto-clang-format
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: DoozyX/clang-format-lint-action@v0.13
      with:
        source: './Source/Runtime'
        exclude: ''
        extensions: 'h,hpp,c,cpp'
        clangFormatVersion: 12
        inplace: True
    - uses: EndBug/add-and-commit@4
      with:
        author_name: Clang Robot
        author_email: clang
        message: ':art: Committing clang-format changes'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
