name: Build

on: [push, pull_request]

jobs:
  unix:
    runs-on: ${{matrix.os}}-latest
    strategy:
      matrix:
        os: [ubuntu, macos]

    steps:
    - uses: actions/checkout@v1
    - name: make test
      run: |
        make -j2 config=sanitize test
        make -j2 config=debug test
        make -j2 config=release test
        make -j2 config=release gltfpack
    - name: make iphone
      if: matrix.os == 'macos'
      run: make -j2 config=iphone
    - name: make coverage
      if: matrix.os == 'ubuntu'
      run: |
        make -j2 config=coverage test
        find . -type f -name '*.gcno' -exec gcov -p {} +
        sed -i -e "s/#####\(.*\)\(\/\/ unreachable.*\)/    -\1\2/" *.gcov
        bash <(curl -s https://codecov.io/bash) -f 'src#*.gcov' -X search -t ${{secrets.CODECOV_TOKEN}}

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [Win32, x64]

    steps:
    - uses: actions/checkout@v1
    - name: cmake configure
      run: cmake . -DBUILD_DEMO=ON -DBUILD_TOOLS=ON -A ${{matrix.arch}}
    - name: cmake test
      shell: bash # necessary for fail-fast
      run: |
        cmake --build . -- -property:Configuration=Debug -verbosity:minimal
        Debug/demo.exe demo/pirate.obj
        cmake --build . -- -property:Configuration=Release -verbosity:minimal
        Release/demo.exe demo/pirate.obj
